### ISSUE TITLE
Design motherboard v1

### ISSUE THREAD

**Issue by chiplet** [VerkkuUkkeli/Kiihdytin#5]
General:
* [x] choose microcontroller [STM32F303RE](https://www.digikey.fi/products/fi/integrated-circuits-ics/embedded-microcontrollers/685?k=STM32F303RE&k=&pkeyword=STM32F303RE&sv=0&pv7=2&sf=0&FV=-8%7C685&quantity=&ColumnSort=0&page=1&pageSize=25)
* [x] board schematics
* [x] board layout

Power Supply:
* It's probably best to use a separate power supply for powering the electromagnet coils and the control circuitry to avoid EMC issues
* [x] regulate required voltages from an external wall wart
  * [x] 3.3V for the microcontroller digital logic
  * [x] 3.3V microcontroller analog reference

Interfaces:
* [x] JTAG
* [x] ST-LINK/V2-1 debugger
* [x] stack connector(s) to electromagnet driver board

TODO:
* [x] Logic level conversion from mcu to RGB

**Comment by Ottis1** [comment]
This is not needed anymore since motherboard functionality is assigned to one of the segments?

**Comment by chiplet** [comment]
MCU selection:
* All analog circuitry (photo gate sensors) shall convert their measures to digital format so the microcontroller does not have to deal with analog signals.

MCU requirements
* [x] Enough GPIO pins (at least to support for adding IO expansion for all required signals)
  * segment indicator LEDs (16)
  * motherboard RGB (1)
  * driver board RGB (1) (can be chained with motherboard RGB)
  * electromagnet control signals (16)
  * debug UART (2)
* [x] UART
* [x] QFP package

The application is not very demanding so pretty much any reasonably sized MCU will do the job. If the I/O lines run out, adding more with expansion modules or shift registers is very easy and can be done without degrading device performance. [STM32F303RE](https://www.digikey.fi/products/fi/integrated-circuits-ics/embedded-microcontrollers/685?k=STM32F303RE&k=&pkeyword=STM32F303RE&sv=0&pv7=2&sf=0&FV=-8%7C685&quantity=&ColumnSort=0&page=1&pageSize=25) is reasonably priced and has extensive analog peripherals if they are deemed necessary in the future. Additionally there is a [nucleo board](https://www.digikey.fi/product-detail/fi/stmicroelectronics/NUCLEO-F303RE/497-15105-ND/5052640) available which can be used as a programmer and makes it easier to get started with firmware development.

**Comment by chiplet** [comment]
## GPIO expansion considerations
Segment indicator LEDs can be driven with the control signals without much issue. A good solution would be to use a LED driver IC with 16 outputs and serial control interface, or maybe even a shift register.

IO expansion ICs allow for bidirectional I/O. This is not necessary for the segment indicators, but would be useful for reading sensors.

Shift registers:
[SN74HC595](https://www.digikey.fi/product-detail/fi/texas-instruments/SN74HC595PWR/296-23258-1-ND/1830780) is currently used for prototyping. These can be chained so 16 indicator LEDs can be controlled over a serial connection with 3 lines in total.

**Comment by chiplet** [comment]
## MCU Implementation

TODO:
* [x] Copy reference design from STM32F3 hardware development [app note](https://www.st.com/resource/en/application_note/dm00070391-getting-started-with-stm32f3-series-hardware-development-stmicroelectronics.pdf)

**Comment by chiplet** [comment]
First revision design is complete!
