### ISSUE TITLE
Segment CAD design

### ISSUE THREAD

**Issue by chiplet** [VerkkuUkkeli/Kiihdytin#9]
CAD design for accelerator segments

TODO and things to consider:
* [x] accommodate segment PCBs
* [x] accommodate photo gate sensor
* [x] accommodate electromagnet
* [ ] ~~places for electrical connectors for inter-module connections (chain units together)~~
* [ ] cable management
* [ ] EMC issues and wiring placement (try to minimise interference by smart cable routing)
* [x] how to manufacture, design with manufacturing in mind (3D printing?)

TODO: add more considerations as they come up

**Comment by chiplet** [comment]
~~## Sensor placement considerations:~~
* [ ] ~~Should the pipe have a hole for mounting the sensors~~
  * [ ] ~~Test if the sensor works through the pipe without mounting holes~~

EDIT: There's no pipe anymore

**Comment by chiplet** [comment]
Relays / FETs are placed on top of the motherboard so there will be no need to try to accommodate them in the segments.

**Comment by kuuotto** [comment]
It seems to me that only the cable management and wiring placement considerations are left in this issue. Controlling the segments happens on the motherboard so there will be no segment PCBs. Also, in my understanding the units will not be chained together in any way. 
3D printing was chosen as the manufacturing method.

**Comment by chiplet** [comment]
Segments have been designed and printed already
